### ISSUE TITLE
test a trained Relight Net on our testing dataset throws error

### ISSUE THREAD

**Issue by Cjkkkk** [zexiangxu/Deep-Relighting#1]
Recently i am reading your paper and i am trying to run your code to test some images. But i run into some trouble ...
environment:
python `2.7.15`
tensorflow `1.3.0`

platform: `manjaro`
running `python run_test.py 90 5 -i ../data/real/2 -o OUTFOLDER -w ../trained/refine -d ../trained/dirs`
throw error
```
testing deg 90 input 5
using weight from: ../trained/refine
rangeNum:  541
[336  51 483 444  54]
TestSize: 541
build downsample
Tensor("downblock0/relu:0", shape=(?, 256, 256, 64), dtype=float32)
Tensor("downblock1/relu:0", shape=(?, 128, 128, 128), dtype=float32)
Tensor("downblock2/relu:0", shape=(?, 64, 64, 256), dtype=float32)
Tensor("downblock3/relu:0", shape=(?, 32, 32, 512), dtype=float32)
expanding dirs
Tensor("expandDirs/Reshape_1:0", shape=(?, 1, 1, 128), dtype=float32)
build center conv
Tensor("convblock/concat:0", shape=(?, 32, 32, 1152), dtype=float32)
build upsample
Tensor("upblock0/concat:0", shape=(?, 64, 64, 768), dtype=float32)
Tensor("upblock1/concat:0", shape=(?, 128, 128, 384), dtype=float32)
Tensor("upblock2/concat:0", shape=(?, 256, 256, 192), dtype=float32)
Tensor("upblock3/concat:0", shape=(?, 512, 512, 89), dtype=float32)
2019-02-24 04:39:18.092457: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-02-24 04:39:18.092483: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-02-24 04:39:18.092492: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-02-24 04:39:18.092499: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-02-24 04:39:18.092506: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
weights restored
test all: 541
0 541
takeData In:  0 None
taken 0
Traceback (most recent call last):
  File "run_test.py", line 77, in <module>
    batchSize=1, bSave=bSave)
  File "/home//Deep-Relighting/relight/CNNRelighting/BaseNN.py", line 297, in Test
    data_inputs, data_outputs = testSet.next_test_batch(batchSize)
  File "/home/Deep-Relighting/relight/CNNRelighting/ParallelLoaderWrapper.py", line 101, in next_test_batch
    self.dataLoader.update_next_test_batch_Ids(batch_size)
  File "/home/Deep-Relighting/relight/CNNRelighting/SameDirsLoader.py", line 192, in update_next_test_batch_Ids
    self._takeData(self.curIds[0] / self.numPerShape)
  File "/home/Deep-Relighting/relight/CNNRelighting/SameDirsLoader.py", line 165, in _takeData
    if self.curInputIDs != None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
any thought about what might cause this problem? Thanks!

**Comment by sylqiu** [comment]
Try to use "is not" in place of "!=". That worked for me.
